obiprivate:
  base_url: http://nomad.pdi-berlin.de/nomad-oasis/api/v1
  directory_path: data
  upload_id: RVy8QIAoQGG6DYNH_UGLCg
oliverbierwagen:
  base_url: http://intra8-02.pdi-berlin.de/nomad-oasis/api/v1
  directory_path: data
  upload_id: vcp7CHk3QtuuCraPD5LQvw
sina:
  base_url: http://intra8-02.pdi-berlin.de/nomad-oasis/api/v1
  directory_path: C:\Users\sina\Nextcloud\_share_Ebna\XRD talaria\20251212 latest\xrd_talaria\data
  upload_id: gq9KCxllSQ6jgAgcDRf-tQ
